Repository yagays/ja-timex, pull requests merged in 2021-08, with the labels that each got.

#12 add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: chore

#13 夜9時・今夜9時のような表現をサポート
  ja_timex/pattern/abstime.py
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
  tests/test_pattern_place.py
  tests/test_timex.py
Labels: enhancement

#14 基準日を設定できるようにする
  ja_timex/pattern/abstime.py
  ja_timex/pattern/duration.py
  ja_timex/pattern/place.py
  ja_timex/pattern/reltime.py
  ja_timex/tag.py
  ja_timex/timex.py
  tests/test_duration_tagger.py
  tests/test_pattern_place.py
  tests/test_reltime_tagger.py
  tests/test_set_tagger.py
  tests/test_tag.py
  tests/test_timex.py
Labels: enhancement

#15 streamlitのアプリでto_datetime/to_durationに対応
  ja_timex/tag.py
  tests/test_timex.py
  tools/timex_checker.py
Labels: chore

#16 基準日時の説明を追加
  docs/docs/reference_datetime.md
  docs/mkdocs.yml
Labels: doc

#17 enable to trigger with release drafter
  .github/workflows/pypi-publish.yml
Labels: chore

#18 typoを修正
  docs/docs/reference_datetime.md
Labels: doc

#22 "半"という表現をサポート
  ja_timex/pattern/duration.py
  ja_timex/pattern/place.py
  tests/test_duration_tagger.py
Labels: enhancement

#23 1年半後や1時間前、半年といった表現をサポート
  ja_timex/number_normalizer.py
  ja_timex/pattern/duration.py
  ja_timex/pattern/reltime.py
  tests/test_duration_tagger.py
  tests/test_number_normalizer.py
  tests/test_reltime_tagger.py
  tests/test_timex.py
Labels: enhancement

#25 先月や半年前などの数字を伴わない表現でto_duration()の計算を修正
  ja_timex/pattern/duration.py
  ja_timex/pattern/reltime.py
  ja_timex/pattern/set.py
  ja_timex/tag.py
  tests/test_tag.py
  tests/test_timex.py
  tests/test_timex_reference.py
Labels: bug

#26 テストを追加
  tests/test_timex_reference.py
  tests/test_timex_to.py
Labels: chore

#27 `to_datetime()`でデフォルトのtimezoneを設定可能にする
  ja_timex/tag.py
  ja_timex/util.py
  tests/test_tag.py
  tests/test_timex_to.py
Labels: enhancement

#28 日付型/時間型への変換方法の説明を追加
  README.md
  docs/docs/introduction.md
  docs/docs/quick_start.md
  docs/docs/to_datetime.md
  docs/mkdocs.yml
Labels: doc

#29 全角括弧の囲みを取得するように修正
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
Labels: bug

#31 東京・千代田区や千春,千夏,千秋,千冬といった表現を取得してしまうバグを修正
  ja_timex/number_normalizer.py
  tests/test_number_normalizer.py
Labels: bug

#32 3日ぶりや10年ぶりといった表現をサポート
  ja_timex/pattern/place.py
  tests/test_reltime_tagger.py
  tests/test_timex.py
Labels: enhancement

#33 時刻表現の後にスペースがある際にTimex.textに含まれないように修正
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
  tests/test_pattern_place.py
  tests/test_timex.py
Labels: bug

#34 12：30といった全角コロンの時間表記を取得できるように修正
  ja_timex/pattern/abstime.py
  tests/test_abstime_tagger.py
Labels: bug

#35 深夜0時や深夜25時といった表現をサポート
  ja_timex/pattern/abstime.py
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
  tests/test_pattern_place.py
Labels: enhancement

#36 早朝6時や10時半といった表現をサポート
  ja_timex/pattern/abstime.py
  ja_timex/pattern/place.py
  setup.cfg
  tests/test_abstime_tagger.py
Labels: enhancement

#37 数字が複数含まれるときに桁数のコンマ処理がされない問題を修正
  ja_timex/number_normalizer.py
  tests/test_number_normalizer.py
Labels: bug

#39 翌週28日が週28日と取得される問題を修正
  ja_timex/timex.py
  tests/test_timex.py
Labels: bug

#40 16世紀頃, 紀元前2世紀近くといった表現をサポート
  ja_timex/pattern/abstime.py
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
Labels: enhancement

#42 末日という表現をサポート
  ja_timex/pattern/place.py
  tests/test_abstime_tagger.py
  tests/test_pattern_place.py
Labels: enhancement

#44 漢数字を変換しない`ignore_kansuji`パラメータを追加
  ja_timex/number_normalizer.py
  ja_timex/timex.py
  tests/test_number_normalizer.py
  tests/test_timex.py
  tests/test_timex_not_applicable.py
Labels: enhancement

#46 Fix typos
  tests/test_pattern_place.py
Labels: chore

#48 数字の途中を日付と誤認識する問題を修正
  ja_timex/timex.py
  ja_timex/util.py
  tests/test_timex_not_applicable.py
  tests/test_util.py
Labels: bug

#49 Filterの導入により対象外の表現を除外
  ja_timex/dictionary/filter_unit.json
  ja_timex/extract_filter.py
  ja_timex/tag.py
  ja_timex/timex.py
  ja_timex/util.py
  tests/test_extract_filter.py
  tests/test_timex.py
  tests/test_timex_not_applicable.py
  tests/test_util.py
Labels: enhancement

#50 0.5ヶ月や3.5年前といった表現の取得ミスを修正
  ja_timex/pattern/place.py
  ja_timex/tag.py
  tests/test_duration_tagger.py
  tests/test_pattern_place.py
  tests/test_reltime_tagger.py
  tests/test_timex_to.py
Labels: bug

#51 stop poetry install before running tox
  .github/workflows/tox.yml
Labels: chore

#52 数字正規化済みのテキストを利用できるように変更
  ja_timex/timex.py
  tools/timex_checker.py
Labels: enhancement

#53 複数の漢数字を処理できない問題を修正
  ja_timex/number_normalizer.py
  tests/test_number_normalizer.py
Labels: bug

#54 ユーザが独自にルールを指定できるCustomTaggerのテストとドキュメントを追加
  docs/docs/custom_tagger.md
  docs/mkdocs.yml
  ja_timex/timex.py
  tests/test_custom_tagger.py
Labels: chore, doc
